#!/usr/bin/env fish
#
# Script to run with entr:
# fd | entr -cp ./dev-daemon

# build project and pipe unminified js into clipboard
rake tmp/integration.js; and cat tmp/integration.js | pbcopy; and notify 'Build successful; Copied to clipboard'; or notifyerr 'Build failed'
